- hosts: devops
  gather_facts: no
  tasks:
    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: delete git
      apt:
        name: git
        state: absent