- hosts: devops
  vars:
    nginx_port: 8090
    root_dir: /usr/share/nginx/html
  become: yes
  tasks:
    - name: make directory files
      ansible.builtin.file:
        path: files
        state: directory

    - name: create-file-content
      ansible.builtin.import_tasks:
        file: create-file-content.yml

    - name: change permissions
      file:
        path: files/index.html
        mode: 0755

    - name: change permissions
      file:
        path: files/nginx.conf
        mode: 0755

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: copy html file
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
        remote_src: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        remote_src: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
