- hosts: devops
  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html
  become: yes
  tasks:
    - name: make directory files
      ansible.builtin.file:
        path: files
        state: directory

    - name: Creating a file index.html with content
      copy:
        dest: files/index.html
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Hello World!</title>
          </head>
          <body>
            <h1>Hello World!</h1>
          </body>
          </html>

    - name: Creating a file nginx.conf with content
      copy:
        dest: files/nginx.conf
        content: |
          events {

          }

          http {
            server {
              listen 80 default_server;
              listen {{nginx_port}} default_server;
            }
          }

    - name: change permissions
      file:
        path: files/index.html
        mode: 0755

    - name: change permissions
      file:
        path: files/nginx.conf
        mode: 0755

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: copy html file
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
        remote_src: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        remote_src: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
