- hosts: devops
#  если включить, что ansible_os_family будет неопределена
#  gather_facts: no
  vars:
    delgit: false
  tasks:
    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian" and delgit

    - name: delete git
      apt:
        name: git
        state: absent
      when: delgit