- hosts: devops
  become: yes

- name: Include install cowsay playbook
  ansible.builtin.import_playbook: plb-inst-cowsay.yml

- name: Include a nginx playbook
  ansible.builtin.import_playbook: plb-install-nginx.yml

- name: Include result cowsay html
  ansible.builtin.import_playbook: plb-cowsay-html.yml
  vars:
    descr: This is server {{ansible_nodename}}!
    root_dir: /usr/share/nginx/html

- name: Include remove cowsay playbook
  ansible.builtin.import_playbook: plb-remove-cowsay.yml